### ISSUE TITLE
Unable to communicate with selected node-Monowallet v0.2.6

### ISSUE THREAD

**Issue by sohosynergy** [bitcoinmono/MonoWallet#1]
Regardless of whether I refresh nodelist none of the nodes work!  I keep getting "Unable to communicate with selected node..." I tried refershing the node list and even added custom nodes but none work!  Oddly the https://github.com/bitcoinmono/bitcoinmono/releases  Version 2.0.6.4 works fine but I have to manually run bitcoinmonod then the zedwallet.exe.  This can really confuse and deter prospective people interested in the BTCMZ coin since the main GUI wallet does not work at all!  I only discovered the zedwallet option by chance.

![monowalletv0 2 6](https://user-images.githubusercontent.com/31788818/67137590-00e14680-f206-11e9-827c-fb12e91322b5.png)

**Comment by bobbieltd** [comment]
Hi ! 11357 is p2p port, incorrect. To use remote node, that node need to open RPC with default port 11358 (—rpc-bind-ip 0.0.0.0 , firewall open for port 11358)

**Comment by sohosynergy** [comment]
Ok wil test again

**Comment by sohosynergy** [comment]
Ok I figured it out..It seems you need to have BOTH 2.0.6.4 and v.0.2.6 set up....if I run the BitcoinMonod from 2.0.6.4, let it sync, then open the v.0.2.6 and point it to 127.0.0.1:11358 it works fine.  It may be a good idea to include the Bitcoinmonod and Bitcoinmono-service files with the v.0.2.6 installer.. that and have the bitcoinmonod automatically open when you open the v.0.2.6 GUI. It will make it a lot less confusing for laypersons.
